version: "3"
services:
  app:
    container_name: main-app
    restart: always
    build: ./movieApp/.
    ports:
      - "7500:7500"

  consumer:
    container_name: consumer
    restart: always
    build: ./consumer/.

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_USERNAME: admin
      MONGO_PASSWORD: example
    ports:
      - '27017:27017'

  # For debug purposes.    
  mongo-express:
      container_name: mongo-admin
      image: mongo-express
      restart: always
      ports:
        - 7501:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  rabbitmq:
      image: 'rabbitmq:3.8-management-alpine'
      ports:
        # The standard AMQP protocol port:
        - '5672:5672'
        # HTTP management UI:
        - '15672:15672'
